# readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

sphinx:
   configuration: docs/conf.py

conda:
  environment: docs/requirements.yaml

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: drugforge-alchemy
    - method: pip
      path: drugforge-cli
    - method: pip
      path: drugforge-data
    - method: pip
      path: drugforge-dataviz
    - method: pip
      path: drugforge-docking
    - method: pip
      path: drugforge-spectrum
    - method: pip
      path: drugforge-ml
    - method: pip
      path: drugforge-modeling
    - method: pip
      path: drugforge-simulation
    - method: pip
      path: drugforge-workflows
