name: drugforge
channels:
  - conda-forge
dependencies:
    - airium
    - alchemiscale-client
    - biopython
    - bokeh
    - boto3
    - cinnabar
    - click
    - codecov
    - distributed
    - docutils[version='>=0.18.1,<0.21']
    - gufe[version='>=1.0.0']
    - imageio
    - kartograf
    - logomaker
    - lomap2
    - matplotlib
    - moto
    - multimethod
    - myst-parser
    - nbsphinx
    - nbsphinx-link
    - netifaces
    - networkx
    - numpy
    - openfe~=1.0
    - openff-forcefields[version='>=2024.04.0']
    - openff-models
    - openff-qcsubmit
    - openff-toolkit
    - openff-units
    - openff-utilities
    - pandas
    - pandoc
    - panel
    - pillow
    - pip
    - plotmol
    - pooch
    - pydantic-settings
    - pydantic[version='>=2.0.0a0']
    - pygifsicle
    - pytest
    - pytest-console-scripts
    - pytest-cov
    - pytest-timeout
    - pytest-xdist
    - python[version='>=3.10,<3.12']
    - pyyaml
    - requests
    - requests-mock
    - rich[version='<14.1.0']
    - scipy[version='>=1.13.1']
    - seaborn
    - semver
    - sigfig
    - sphinx
    - sphinx_rtd_theme
    - tqdm
    - typing-extensions
    - pip:
        - sphinx-collections
