name: docs
channels:
  - openeye
  - conda-forge
dependencies:
  # install drugforge from conda-forge

  # docs
  - sphinx
  - sphinx_rtd_theme
  - myst-parser
  - nbsphinx
  - nbsphinx-link
  - pandoc
  - docutils >=0.18.1,<0.21 # see #1260
