name: drugforge
channels:
  - openeye
  - conda-forge
dependencies:
  - airium
  - click
  - imageio
  - logomaker
  - matplotlib
  - mdtraj
  - multimethod
  - pandas
  - pillow
  - pydantic[version='>=2.0.0a0']
  - pygifsicle
  - pymol-open-source
  - alchemiscale-client
  - bokeh
  - cinnabar
  - kartograf
  - lomap2
  - netifaces
  - networkx
  - numpy
  - openeye-toolkits
  - openfe~=1.0
  - openff-qcsubmit
  - openff-toolkit
  - openff-units
  - openff-utilities
  - panel
  - perses
  - pip
  - plotmol
  - pooch
  - pyyaml
  - rdkit
  - requests-mock
  - rich[version='<14.1.0']
  - tqdm
  - typing-extensions
  - boto3
  - dask
  - distributed
  - mdanalysis
  - moto
  - plip
  - pydantic-settings
  - python[version='>=3.10,<3.12']
  - requests
  - sigfig
  - mtenn[version='>=0.6.3']
  - semver
  - openff-forcefields[version='>=2024.04.0']
  - openmmforcefields[version='>=0.13.0']
  - openmmtools
  - pytorch
  - scipy[version='>=1.13.1']
  - seaborn
  - docutils[version='>=0.18.1,<0.21']
  - myst-parser
  - nbsphinx
  - nbsphinx-link
  - pandoc
  - sphinx
  - sphinx_rtd_theme

  - pip:
      - sphinx-collections